const env = {
    EXPRESS_PORT: process.env.EXPRESS__PORT,
    EXPRESS_URL_FE: process.env.EXPRESS__URL__FE,
    EXPRESS_URL_MONGODB: process.env.EXPRESS__URL__MONGODB,
    EXPRESS_SECRET_KEY: process.env.EXPRESS__SECRET__KEY,
    EXPRESS_ROUNDS_HASH: process.env.EXPRESS__ROUNDS__HASH,
    EXPRESS_TEMPLATE_EMAIL: process.env.EXPRESS__TEMPLATE__EMAIL,
    EXPRESS_SERVICE_EMAIL: process.env.EXPRESS__SERVICE__EMAIL,
    EXPRESS_PUBLIC_KEY_EMAIL: process.env.EXPRESS__PUBLIC__KEY__EMAIL,
    EXPRESS_PRIVATE_KEY_EMAIL: process.env.EXPRESS__PRAVATE__KEY__EMAIL,
    EXPRESS_NAME_EMAIL_KEY_EMAIL: process.env.EXPRESS__NAME__EMAIL__KEY__EMAIL,
    EXPRESS_REPLY_EMAIL_KEY_EMAIL: process.env.EXPRESS__REPLAY__EMAIL__KEY__EMAIL,
    EXPRESS_SECRET_TOKEN: process.env.EXPRESS__SECRET__TOKEN,
    EXPRESS_DAY_TOKEN: process.env.EXPRESS__DAY__TOKEN,
    EXPRESS_COOKIES_SECURE: process.env.EXPRESS__COOKIES__SECURE,
    EXPRESS_COOKIES_ONLYHTTP: process.env.EXPRESS__COOKIES__ONLYHTTP,
    EXPRESS__COOKIES__SAMESITE: process.env.EXPRESS__COOKIES__SAMESITE
};


module.exports = env;
